In [1]:
import numpy as np

In [2]:
# Initialize states and policy

def initialization():
    num_rows = 4
    num_cols = 4
    states = []
    for i in range(num_rows):
        for j in range(num_cols):
            states.append((i,j))
    terminal_states = [(0,0),(3,3)]
    return states,terminal_states

In [3]:
# Policy evaluation for equiprobable random policy
def policy_evaluation(states,terminal_states):
    num_iterations = 0
    V = {}
    V1 = {}
    for state in states:
        V[state] = 0
        V1[state] = 0
    # Loop for convergence of V
    while num_iterations < 100:
        # Loops to update all states
        V1 = {}
        for state in states:
            V1[state] = 0
        for state in states:
            if state in terminal_states:
                continue
            V1[state] += 0.25*(-1 + V[(state[0],max(0,state[1]-1))])
            V1[state] += 0.25*(-1 + V[(state[0],min(3,state[1]+1))])
            V1[state] += 0.25*(-1 + V[(max(0,state[0]-1),state[1])])
            V1[state] += 0.25*(-1 + V[(min(3,state[0]+1),state[1])])
                
        V = V1
        num_iterations += 1

    return V

In [4]:
states,terminal_states = initialization()

V1 = policy_evaluation(states,terminal_states)

# Convert value function from dictionary to a numpy array 
V = np.zeros((4,4))
for state in states:
    V[state[0]][state[1]] = V1[state]
    
# Print value function
print(np.round(V))

[[  0. -14. -20. -22.]
 [-14. -18. -20. -20.]
 [-20. -20. -18. -14.]
 [-22. -20. -14.   0.]]
