In [1]:
import numpy as np

In [2]:
# Initialize states and policy

def initialization():
    V = np.zeros([4,4])
    return V

In [3]:
# Policy evaluation for equiprobable random policy
def policy_evaluation(V):
    num_iterations = 0
    V = np.zeros([4,4])
    V1 = np.zeros([4,4])
    # Loop for convergence of V
    while num_iterations < 1000:
        # Loops to update all states
        for i in range(0,4):
            for j in range(0,4):
                # Actions that take the agent out of the grid leave it unchanged
                if (i == 0 and j == 0) or (i == 3 and j == 3):
                    V1[i][j] = 0
                    continue
                elif i == 0 and j == 3:
                    V1[i][j] = 0.25*(-1 + V[i][j-1]) + 0.25*(-1 + V[i+1][j]) + 2*0.25*(-1 + V[i][j])
                elif i == 3 and j == 0:
                    V1[i][j] = 0.25*(-1 + V[i-1][j]) + 0.25*(-1 + V[i][j+1]) + 2*0.25*(-1 + V[i][j])
                elif i == 0 and j != 0:
                    V1[i][j] = 0.25*(-1 + V[i][j-1]) + 0.25*(-1 + V[i][j+1]) + 0.25*(-1 + V[i+1][j]) + 0.25*(-1 + V[i][j])
                elif i == 3 and j != 3:
                    V1[i][j] = 0.25*(-1 + V[i][j-1]) + 0.25*(-1 + V[i][j+1]) + 0.25*(-1 + V[i-1][j]) + 0.25*(-1 + V[i][j])
                elif j == 0 and i != 0:
                    V1[i][j] = 0.25*(-1 + V[i][j+1]) + 0.25*(-1 + V[i-1][j]) + 0.25*(-1 + V[i+1][j]) + 0.25*(-1 + V[i][j])
                elif j == 3 and i != 3:
                    V1[i][j] = 0.25*(-1 + V[i][j-1]) + 0.25*(-1 + V[i-1][j]) + 0.25*(-1 + V[i+1][j]) + 0.25*(-1 + V[i][j])
                else:
                    V1[i][j] = 0.25*(-1 + V[i-1][j]) + 0.25*(-1 + V[i+1][j]) + 0.25*(-1 + V[i][j-1]) + 0.25*(-1 + V[i][j+1])
        
        V = V1
        num_iterations += 1
    
    return V

In [4]:
V = initialization()

V = policy_evaluation(V)

# Print value function
print(np.round(V))

[[  0. -14. -20. -22.]
 [-14. -18. -20. -20.]
 [-20. -20. -18. -14.]
 [-22. -20. -14.   0.]]
